name: Periodic Workflow

on:
  schedule:
    #cada 5 minutos de Lunes a viernes
    - cron: '*/5 * * * 1-5'

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
    #indica nombre del propietario del repositorio
      - run: echo ${{github.repository_owner}}
    #indica nombre del repositorio
      - run: echo ${{github.repository}}
    #indica el nombre de quien corre el job
      - run: echo ${{runner.name}}
    #indica OS en donde se ejecuta el trabajo  
      - run: echo ${{runner.os}}
    #indica el id del job (job_id) actual
      - run: echo ${{github.job}}
    
    
      